---
echo: false
warning: false
fig-width: 8
fig-height: 3
---

# Corvallis, Oregon

```{r}
#| include: false
library(tidyverse)
library(here)
```


```{r}
highlight_color <- "#FF5733" # A bright color for highlighting
```
```{r}
corvallis_monthly <- read_csv(here("data", "tmean_monthly.csv")) |> 
  filter(city == "Corvallis")
corvallis_normals <- read_csv(here("data", "tmean_normals.csv")) |> 
  filter(city == "Corvallis")
```

```{r}
this_month <- as.Date("2025-05-01")
this_tmean <- corvallis_monthly |>
  filter(date == this_month) |>
  pull(tmean)
normal_tmean <- corvallis_normals |>
  filter(month == month(this_month)) |>
  pull(tmean)
this_month_diff <- this_tmean - normal_tmean
direction <- ifelse(this_month_diff > 0, "warmer", "cooler")
```

`{r} month(this_month, label = TRUE)` `{r} year(this_month)`  was `{r} round(abs(this_month_diff), 1)`°C `{r} direction` than usual.


```{r}
corvallis_monthly |>
  ggplot(aes(month(date), tmean)) +
  geom_line(aes(group = year(date)), alpha = 0.2) +
  geom_line(
    aes(x = month),
    data = corvallis_normals,
  ) +
  geom_line(
    data = corvallis_monthly |> filter(year(date) == 2025),
    color = highlight_color
  ) +
  geom_point(
    data = corvallis_monthly |>
      filter(date == this_month),
    color = highlight_color
  ) +
  scale_x_continuous(
    breaks = 1:12,
    labels = month.abb
  ) +
  labs(
    x = "",
    y = "Mean Temperature (°C)"
  ) +
  theme_minimal()
```
