---
title: "Untitled"
format: html
---


```{r}
library(prism)
library(terra)
library(tidyverse)
library(here)
download <- FALSE
```


```{r}
months <- 1:12 |> set_names(month.abb)
```

```{r}
prism_set_dl_dir(here("data-raw", "prism"))
```

## Download from PRISM archive
```{r}
if (download) {
  get_prism_normals(
    type = "tmean",
    resolution = "4km",
    mon = 1:12,
    keepZip = FALSE
  )
}
```


```{r}
if (download) {
  get_prism_monthlys(
    "tmean",
    years = (2025 - 30):2025,
    mon = 1:12,
    keepZip = FALSE
  )
}
```

## Get raster stacks for monthly normals and monthly data

```{r}
tmean_monthly_normals <- prism_archive_subset(
  "tmean",
  mon = 1:12,
  temp_period = "monthly normals",
  resolution = "4km"
)
pd_get_md(tmean_monthly_normals) |>
  write_csv(here("data", "tmean_normals_metadata.csv"))
tmean_monthly_normals <- pd_to_file(tmean_monthly_normals)
tmean_monthly_normals_raster <- rast(tmean_monthly_normals)
```

```{r}
tmean_monthly <- prism_archive_subset(
  "tmean",
  mon = 1:12,
  years = (2025 - 30):2025,
  temp_period = "monthly"
)
pd_get_md(tmean_monthly) |>
  write_csv(here("data", "tmean_monthly_metadata.csv"))
tmean_monthly <- pd_to_file(tmean_monthly)
tmean_monthly_raster <- rast(tmean_monthly)
```

## Extract for lat and lng of cities

```{r}
cities <- read_csv(here("data", "top_50_cities.csv"))
cities_vec <- cities |>
  select(city, lat, lng) |>
  vect(geom = c("lng", "lat"), crs = "WGS84")
```

### Normals 

```{r}
tmean_normals <- terra::extract(
  tmean_monthly_normals_raster,
  cities_vec,
  bind = TRUE
)

get_month <- function(x) {
  months <- 1:12 |> set_names(month.abb)
  x |> pd_get_name() |> str_sub(1, 3) |> months[i = _]
}

tmean_normals <-
  tmean_normals |>
  as_tibble() |>
  pivot_longer(
    cols = -city,
    names_to = "month",
    values_to = "tmean"
  ) |>
  mutate(month = get_month(month))
```

## Monthlies

```{r}
tmean_monthlies <- terra::extract(
  tmean_monthly_raster,
  cities_vec,
  bind = TRUE
)

tmean_monthlies <-
  tmean_monthlies |>
  as_tibble() |>
  pivot_longer(
    cols = -city,
    names_to = "date",
    values_to = "tmean"
  ) |>
  mutate(date = pd_get_date(date) |> as.Date())
```



```{r}
tmean_normals |>
  filter(city == "Corvallis") |>
  ggplot(aes(month, tmean)) +
  geom_point() +
  labs(
    title = "Corvallis, OR Monthly Mean Temperature Normals",
    x = "Month",
    y = "Mean Temperature (°C)"
  ) +
  theme_minimal()
```


```{r}
tmean_monthlies |>
  filter(city == "Corvallis") |>
  ggplot(aes(month(date), tmean)) +
  geom_line(aes(group = year(date)), alpha = 0.2) +
  geom_line(
    data = tmean_monthlies |>
      filter(city == "Corvallis") |>
      filter(year(date) == 2025),
    color = "red"
  ) +
  scale_x_continuous(
    breaks = 1:12,
    labels = month.abb
  ) +
  labs(
    x = "",
    y = "Mean Temperature (°C)"
  ) +
  theme_minimal()
```


```{r}
tmean_normals <- tmean_normals |>
  rename(tmean_normal = tmean)

tmean_monthlies |>
  mutate(
    month = month(date),
    year = year(date)
  ) |>
  left_join(tmean_normals, by = c("city", "month")) |>
  mutate(
    tmean_diff = tmean - tmean_normal,
    tmean_direction = ifelse(tmean_diff > 0, "warmer", "cooler"),
    tmean_diff = abs(tmean_diff)
  ) |>
  write_csv(here("data", "tmean-oregon.csv"))
```
